version: '3.8'
services:
  db:
    container_name: db-sge
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'sge_moviles'
      MYSQL_USER: 'SGE_admin'
      MYSQL_PASSWORD: 'alejandroanibalpablo'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - data:/var/lib/mysql
volumes:
  data: